<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXinVgOL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXinVgOL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXinVgOL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXinVgOL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXinVgOL\App_KernelDevDebugContainer([
    'container.build_hash' => 'XinVgOL',
    'container.build_id' => 'f3998300',
    'container.build_time' => 1713198489,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXinVgOL');
