<?php

namespace ContainerXinVgOL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7R6cNzgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7R6cNzg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7R6cNzg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LuckyController::getMessage' => ['privates', '.service_locator.qlTmxuJ', 'get_ServiceLocator_QlTmxuJService', true],
            'App\\Controller\\NotaController::list' => ['privates', '.service_locator.x2nWtwr', 'get_ServiceLocator_X2nWtwrService', true],
            'App\\Controller\\NotaController::new' => ['privates', '.service_locator.Faif7QS', 'get_ServiceLocator_Faif7QSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LuckyController:getMessage' => ['privates', '.service_locator.qlTmxuJ', 'get_ServiceLocator_QlTmxuJService', true],
            'App\\Controller\\NotaController:list' => ['privates', '.service_locator.x2nWtwr', 'get_ServiceLocator_X2nWtwrService', true],
            'App\\Controller\\NotaController:new' => ['privates', '.service_locator.Faif7QS', 'get_ServiceLocator_Faif7QSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LuckyController::getMessage' => '?',
            'App\\Controller\\NotaController::list' => '?',
            'App\\Controller\\NotaController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LuckyController:getMessage' => '?',
            'App\\Controller\\NotaController:list' => '?',
            'App\\Controller\\NotaController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
