# config/validator/validation.yaml
App\Entity\Pelicula:
    properties:
        titulo:
            - Length:
                min: 5
                
                minMessage: 'Your first name must be at least {{ limit }} characters long'
               