<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBLeurfX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBLeurfX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBLeurfX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBLeurfX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBLeurfX\App_KernelDevDebugContainer([
    'container.build_hash' => 'BLeurfX',
    'container.build_id' => 'c8be2687',
    'container.build_time' => 1713799869,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBLeurfX');
