# config/validator/validation.yaml
App\Entity\Pelicula:
    properties:
        titulo:
            - Length:
                min: 5
                
                minMessage: 'El titulo debe tener al menos {{ limit }} caracteres'
               