<?php

namespace ContainerBLeurfX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_046m5aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.04_6m5a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.04_6m5a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fecha' => ['privates', '.errored..service_locator.04_6m5a.DateTime', NULL, 'Cannot autowire service ".service_locator.04_6m5a": it references class "DateTime" but no such service exists.'],
        ], [
            'fecha' => 'DateTime',
        ]);
    }
}
