<?php

namespace ContainerBLeurfX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HwuC0IPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hwuC0IP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hwuC0IP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nota' => ['privates', '.errored..service_locator.hwuC0IP.App\\Entity\\Nota', NULL, 'Cannot autowire service ".service_locator.hwuC0IP": it needs an instance of "App\\Entity\\Nota" but this type has been excluded in "config/services.yaml".'],
        ], [
            'nota' => 'App\\Entity\\Nota',
        ]);
    }
}
